name: Build Folia

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: PaperMC/Folia
          path: Folia-master

      # Устанавливаем Java
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: '21'

      # Переходим в директорию проекта
      - name: Change directory to Folia-master
        run: cd Folia-master
        
      # Настраиваем Git
      - name: Configure Git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          
      # Выполняем команды Gradle для сборки
      - name: Apply patches
        run: ./gradlew applyPatches
        working-directory: Folia-master

      - name: Create Mojmap Bundler Jar
        run: ./gradlew createMojmapBundlerJar
        working-directory: Folia-master

      # Получаем имя файла .jar
      - name: Get JAR filename
        id: get_jar
        run: |
          cd Folia-master/build/libs
          JAR_NAME=$(ls *.jar | head -n 1)
          echo "jar_name=$JAR_NAME" >> $GITHUB_ENV

      # Загружаем .jar файл в артефакты с именем файла
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.jar_name }}
          path: Folia-master/build/libs/${{ env.jar_name }}
